seed: 42
elem_per_bin: 50
min_ef: 0
max_ef: 100
video_ex_path: "./data/balancing_samples/videos"
csv_ex_path: "./data/balancing_samples/EFscores.csv"
label_key: "TargetEF"

dataset:
  data_path: "./data/EchoNet-Dynamic"
  deactivate_cache: True
  target_fps: 32 # max 64
  resample_to_num_frames_fps: True
  image_size: 112 # max 112
  seconds: 2

dataloader:
  batch_size: 64
  num_workers: 64

trainer:
  max_epochs: 100
  lr: 1e-4

wandb:
  project: "MICCAI23"
  entity: "hreynaud"
  interval: 10

checkpoint:
  path: "./outputs/ef_regression_balance"
